TestApp/Models/CUSTOMER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.CUSTOMER_ID = "5";
            this.MAIN_ORDER = new HashSet<MAIN_ORDER>();
            this.PAYMENTs = new HashSet<PAYMENT>();
            this.ORDER_HISTORY = new HashSet<ORDER_HISTORY>();
            this.ORDER_DETAIL = new HashSet<ORDER_DETAIL>();
        }
    
        public string CUSTOMER_ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string ADDRESS { get; set; }
        public string POST_CODE { get; set; }
        public string CONTACT_NO { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string SALT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAIN_ORDER> MAIN_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT> PAYMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_HISTORY> ORDER_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAIL> ORDER_DETAIL { get; set; }
    }
}

TestApp/Controllers/CUSTOMERsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestApp.Models;
using System.Web.Configuration;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace TestApp.Controllers

{
    public class CUSTOMERsController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: CUSTOMERs
        public ActionResult Index()
        {
            return View(db.CUSTOMERs.ToList());
        }

        public ActionResult ChangePass()
        {
            return View();
        }

        public ActionResult ChangePass(string pass, string pass1, string id)
        {
            CUSTOMER a = new CUSTOMER();
            var regexItem = new Regex("^[a-zA-Z0-9 ]+$");

            if (regexItem.IsMatch(pass))
            {
                string random = RandomString(5);
                var UserPass = random + a.PASSWORD;
                string hash = sha256(UserPass);
                a.SALT = random;
                a.PASSWORD = hash;
                db.CUSTOMERs.Add(a);

                db.SaveChanges();

            }
            else
            {
                ModelState.AddModelError("", "Password contains invalid character !@#$%^&*()?");
            }
            return  RedirectToAction("http://localhost:62750/Home/Index");
        }

        // GET: CUSTOMERs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUSTOMER cUSTOMER = db.CUSTOMERs.Find(id);
            if (cUSTOMER == null)
            {
                return HttpNotFound();
            }
            return View(cUSTOMER);
        }

        // GET: CUSTOMERs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CUSTOMERs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CUSTOMER_ID,NAME,SURNAME,ADDRESS,POST_CODE,CONTACT_NO,USERNAME,PASSWORD,EMAIL")] CUSTOMER cUSTOMER)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    var regexItem = new Regex("^[a-zA-Z0-9 ]+$");

                    if (regexItem.IsMatch(cUSTOMER.PASSWORD))
                    {
                        string random = RandomString(5);
                        var UserPass = random + cUSTOMER.PASSWORD;
                        string hash = sha256(UserPass);
                        cUSTOMER.SALT = random;
                        cUSTOMER.PASSWORD = hash;
                        db.CUSTOMERs.Add(cUSTOMER);

                        db.SaveChanges();
                        
                    }
                    else
                    {
                        ModelState.AddModelError("", "Password contains invalid character !@#$%^&*()?");
                    }



                    return RedirectToAction("Login", "CUSTOMERs", new { area = "" });



                }
                catch (Exception x)
            {
                ModelState.AddModelError("", "Username or Password Doesn't Exist");
            }

        }
            else
            {


            }

            return View(cUSTOMER);
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(CUSTOMER cUSTOMER)
        {
            using (Entities1 db = new Entities1())
            {
                CUSTOMER a = new CUSTOMER();
                var UserInput = db.CUSTOMERs.FirstOrDefault(b => b.EMAIL == cUSTOMER.EMAIL);
                if (UserInput != null && UserInput.PASSWORD == sha256(UserInput.SALT + cUSTOMER.PASSWORD))
                {
                    try
                    {
                        Session["CustomerId"] = UserInput.CUSTOMER_ID.ToString();
                        //Session["Email"] = UserInput.EMAIL.ToString();
                        Session["Name"] = UserInput.NAME.ToString();
                        //return RedirectToAction("Index");
                        return Redirect("http://localhost:62750/Home/Index");
                    }
                    catch (Exception x)
                    {
                        ModelState.AddModelError("", "Email or Password Doesn't Exist");
                    }
                }
                else
                {
                    
                
                        ModelState.AddModelError("", "Email or password is wrong");
                    }
               
            }
            return View(cUSTOMER);
        }

       

        
        public ActionResult Logout()
        {
            Session.Clear();
            
            return Redirect("http://localhost:62750/Home/Index");
        }
        // GET: CUSTOMERs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUSTOMER cUSTOMER = db.CUSTOMERs.Find(id);
            if (cUSTOMER == null)
            {
                return HttpNotFound();
            }
            return View(cUSTOMER);
        }

        // POST: CUSTOMERs/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CUSTOMER_ID,NAME,SURNAME,ADDRESS,POST_CODE,CONTACT_NO,PASSWORD,EMAIL")] CUSTOMER cUSTOMER)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cUSTOMER).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("http://localhost:62750/ORDER_HISTORY/Index");
            }
            return View(cUSTOMER);
        }

        // GET: CUSTOMERs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUSTOMER cUSTOMER = db.CUSTOMERs.Find(id);
            if (cUSTOMER == null)
            {
                return HttpNotFound();
            }
            return View(cUSTOMER);
        }

        // POST: CUSTOMERs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            CUSTOMER cUSTOMER = db.CUSTOMERs.Find(id);
            db.CUSTOMERs.Remove(cUSTOMER);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        static string sha256(string password)
        {
            System.Security.Cryptography.SHA256Managed crypt = new System.Security.Cryptography.SHA256Managed();
            System.Text.StringBuilder hash = new System.Text.StringBuilder();
            byte[] crypto = crypt.ComputeHash(Encoding.UTF8.GetBytes(password), 0, Encoding.UTF8.GetByteCount(password));
            foreach (byte theByte in crypto)
            {
                hash.Append(theByte.ToString("x2"));
            }
            return hash.ToString();
        }
        private static Random random = new Random((int)DateTime.Now.Ticks);
        private string RandomString(int size)
        {
            StringBuilder builder = new StringBuilder();
            char ch;
            for (int i = 0; i < size; i++)
            {
                ch = Convert.ToChar(Convert.ToInt32(Math.Floor(26 * random.NextDouble() + 65)));
                builder.Append(ch);
            }

            return builder.ToString();
        }
    }
}

TestApp/Controllers/ORDER_HISTORYController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestApp.Models;

namespace TestApp.Controllers
{
    public class ORDER_HISTORYController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: ORDER_HISTORY
        public ActionResult Index()
        {
            var oRDER_HISTORY = db.ORDER_HISTORY.Include(o => o.CUSTOMER);
            return View(oRDER_HISTORY.ToList());
        }
        //public ActionResult Track()
        //{
        //    var oRDER = db.ORDER_HISTORY.Include(m => m.CUSTOMER);
        //    return View(oRDER.ToList());
        //}
        // GET: ORDER_HISTORY/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDER_HISTORY oRDER_HISTORY = db.ORDER_HISTORY.Find(id);
            if (oRDER_HISTORY == null)
            {
                return HttpNotFound();
            }
            return View(oRDER_HISTORY);
        }

        // GET: ORDER_HISTORY/Create
        public ActionResult Create()
        {
            ViewBag.CUSTOMER_ID = new SelectList(db.CUSTOMERs, "CUSTOMER_ID", "NAME");
            return View();
        }

        // POST: ORDER_HISTORY/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ORDER_HISTORY_ID,ORDER_ID,CUSTOMER_ID,TOTALCOST,ORDER_DATE,RIDER_ID")] ORDER_HISTORY oRDER_HISTORY)
        {
            if (ModelState.IsValid)
            {
                db.ORDER_HISTORY.Add(oRDER_HISTORY);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CUSTOMER_ID = new SelectList(db.CUSTOMERs, "CUSTOMER_ID", "NAME", oRDER_HISTORY.CUSTOMER_ID);
            return View(oRDER_HISTORY);
        }

        // GET: ORDER_HISTORY/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDER_HISTORY oRDER_HISTORY = db.ORDER_HISTORY.Find(id);
            if (oRDER_HISTORY == null)
            {
                return HttpNotFound();
            }
            ViewBag.CUSTOMER_ID = new SelectList(db.CUSTOMERs, "CUSTOMER_ID", "NAME", oRDER_HISTORY.CUSTOMER_ID);
            return View(oRDER_HISTORY);
        }

        // POST: ORDER_HISTORY/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ORDER_HISTORY_ID,ORDER_ID,CUSTOMER_ID,TOTALCOST,ORDER_DATE,RIDER_ID")] ORDER_HISTORY oRDER_HISTORY)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oRDER_HISTORY).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CUSTOMER_ID = new SelectList(db.CUSTOMERs, "CUSTOMER_ID", "NAME", oRDER_HISTORY.CUSTOMER_ID);
            return View(oRDER_HISTORY);
        }

        // GET: ORDER_HISTORY/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDER_HISTORY oRDER_HISTORY = db.ORDER_HISTORY.Find(id);
            if (oRDER_HISTORY == null)
            {
                return HttpNotFound();
            }
            return View(oRDER_HISTORY);
        }

        // POST: ORDER_HISTORY/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ORDER_HISTORY oRDER_HISTORY = db.ORDER_HISTORY.Find(id);
            db.ORDER_HISTORY.Remove(oRDER_HISTORY);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestApp/Views/CUSTOMERs/ChangePass.cshtml
@model TestApp.Models.CUSTOMER

@{
    ViewBag.Title = "ChangePass";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        <div class="form-group">
                @Html.Label("Old Password", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.Password("password1", "", new { id = "password1", Textmode = "Password" })
                    @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                </div>
            </div>

        <div class="form-group">
            @Html.Label("New Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Password("password", "", new { id = "password", Textmode = "Password" })
                @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Re-Enter New Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Password("newpassword", "", new { id = "newpassword", Textmode = "Password" })
                @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Save", "ChangePass", new { pass = })
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "Index", "ORDER_HISTORY")
</div>

TestApp/Views/CUSTOMERs/Create.cshtml
@model TestApp.Models.CUSTOMER
@*@model System.Web.Mvc.HandleErrorInfo
<h1 class="text-danger">Error.@Model.Exception.Message</h1>
<h2 class="text-danger">Error re mlk</h2>
@Html.ActionLink("Back", @Model.ActionName, @Model.ControllerName)*@


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        
        @*<div class="form-group">
            @Html.LabelFor(model => model.CUSTOMER_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CUSTOMER_ID,"5", new { htmlAttributes = new  { @Value = "5"}  })
                @Html.ValidationMessageFor(model => model.CUSTOMER_ID, " ", new { @class = "text-danger" })
            </div>
        </div>*@
        
        
        <div class="form-group">
            @Html.LabelFor(model => model.NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SURNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SURNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SURNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.POST_CODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.POST_CODE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.POST_CODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CONTACT_NO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CONTACT_NO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CONTACT_NO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" >
            @Html.LabelFor(model => model.PASSWORD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" >
                @Html.EditorFor(model => model.PASSWORD, new { htmlAttributes = new { @class = "form-control password"  } })
                @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

TestApp/Views/CUSTOMERs/Delete.cshtml
@model TestApp.Models.CUSTOMER

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CUSTOMER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SURNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SURNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ADDRESS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.POST_CODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.POST_CODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CONTACT_NO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONTACT_NO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PASSWORD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PASSWORD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TestApp/Views/CUSTOMERs/Details.cshtml
@model TestApp.Models.CUSTOMER

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CUSTOMER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SURNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SURNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ADDRESS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.POST_CODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.POST_CODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CONTACT_NO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONTACT_NO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PASSWORD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PASSWORD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CUSTOMER_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TestApp/Views/CUSTOMERs/Edit.cshtml
@model TestApp.Models.CUSTOMER

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CUSTOMER</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CUSTOMER_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SURNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SURNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SURNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.POST_CODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.POST_CODE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.POST_CODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CONTACT_NO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CONTACT_NO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CONTACT_NO, "", new { @class = "text-danger" })
            </div>
        </div>

        

        @*<div class="form-group">
            @Html.LabelFor(model => model.PASSWORD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PASSWORD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "Index","ORDER_HISTORY")
</div>

TestApp/Views/CUSTOMERs/Logout.cshtml
@model TestApp.Models.CUSTOMER

@{
    ViewBag.Title = "Logout";
}

<h2>Logout</h2>