TestApp/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestApp.Models;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;


namespace TestApp.Controllers
{
    public class ShoppingCartController : Controller
    {
        int BusketItems = 0;
        double total = 0;
        int i = 0;

        
        
        private Entities1 pz = new Entities1();
       
        public ActionResult Index()
        {
            return View();
        }

        public class Size
        {
            public int Prise { get; set; }
            public string ItemSize { get; set; }
        }
        public IEnumerable<Size> SizeOptions =
       new List<Size>
       {
            new Size {Prise = 0, ItemSize = "Small"},
            new Size {Prise = 3, ItemSize = "Medium"},
            new Size {Prise = 6, ItemSize = "Large"}
       };



        private int isExisting(int id)
        {
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Pr.SIZE_ID == id.ToString())                
                    return i;
                
                
             }
            return -1;
        }

        public ActionResult AddQt(int id)
        {
            int index = isExisting(id);
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            cart[index].Quantity++;
            Session["cart"] = cart;
            total = Convert.ToDouble(Session["Total"]) + Convert.ToDouble(cart[index].Pr.UNIT_PRICE);
            Session["Total"] = total.ToString();
            return View("Cart");
        }
        public ActionResult RemoveQt(int id)
        {
            int index = isExisting(id);
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            cart[index].Quantity--;
            Session["cart"] = cart;
            total = Convert.ToDouble(Session["Total"]) - Convert.ToDouble(cart[index].Pr.UNIT_PRICE);
            Session["Total"] = total.ToString();
            return View("Cart");
        }
        public ActionResult Delete(int id)
        {
            //ITEM_SIZE Is = new ITEM_SIZE();
            int index = isExisting(id);
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            //double price = Convert.ToDouble(Is);
            //int index = cart.IndexOf(id);
            cart.RemoveAt(index);
            Session["cart"] = cart;
            total = Convert.ToDouble(Session["Total"]) - Convert.ToDouble(cart[index].Pr.UNIT_PRICE * cart[index].Quantity);
            Session["Total"] = total.ToString();
            
            
            return View("Cart");


        }

        public ActionResult Busket()
        {

            return View("Cart");
        }

        public ActionResult OrderNow(int id)
        {
            //BusketItems++;
            //Session["BusketItems"] = BusketItems.ToString();
            if (Session["cart"] == null)
            {
                
                ITEM_SIZE Is = new ITEM_SIZE();
                
                    //double price = Convert.ToDouble(Is.UNIT_PRICE);
                    List<CartItem> cart = new List<CartItem>();
                    cart.Add(new CartItem(pz.ITEM_SIZE.Find(id.ToString()), 1));
                    Session["cart"] = cart;
                    BusketItems = 1;
                    Session["BusketItems"] = BusketItems.ToString();
                    total = Convert.ToDouble(cart[0].Pr.UNIT_PRICE);
                    Session["Total"] = total.ToString();
                    //string url = Request.Url.AbsolutePath;
                    //Session["URL"] = url;
                    
                
            }
            else
            {
                //ITEM_SIZE Is = new ITEM_SIZE();
                List<CartItem> cart = (List<CartItem>)Session["cart"];
                int index = isExisting(id);
                //double price = Convert.ToDouble(Is);
                if (index == -1)
                    
                    cart.Add(new CartItem(pz.ITEM_SIZE.Find(id.ToString()), 1));
                else
                    cart[index].Quantity++;

                
                Session["cart"] = cart;
                BusketItems = cart.Count;
                Session["BusketItems"] = BusketItems.ToString();
                i = BusketItems - 1;
                total = Convert.ToDouble(Session["Total"]) + Convert.ToDouble(cart[i].Pr.UNIT_PRICE);
                Session["Total"] = total.ToString();
            }
            
           
            //ScriptManager.RegisterStartupScript( this , this.GetType(), "testScript", "autoclosable - btn - info", true);
            return Redirect(Request.UrlReferrer.ToString()); 
            //Request.UrlReferrer.ToString()
        }

        //[HttpPost]
        
        //public ActionResult Pay(ORDER_DETAIL Order)
        //{
        //    if (Session["CustomerId"] != null)
        //    {
        //        // int test = 299;
        //        List<CartItem> cart = (List<CartItem>)Session["cart"];
        //        for (int i = 0; i < cart.Count; i++)
        //        {

        //            // Order.ORDER_DETAIL_ID = test.ToString();
        //            Order.CUSTOMER_ID = Session["CustomerId"].ToString();
        //            Order.ITEM_ID = cart[i].Pr.ITEM_ID;
        //            Order.QUANTITY = cart[i].Quantity.ToString();
        //            Order.TOTALCOST = cart[i].Pr.UNIT_PRICE* cart[i].Quantity;
        //            pz.ORDER_DETAIL.Add(Order);
        //            pz.SaveChanges();
        //            // test++;

        //        }
        //        return Redirect("http://localhost:62750/ORDER_DETAIL/Index");
        //    }
        //    else
        //    {
        //        return Redirect("http://localhost:62750/CUSTOMERs/Login");
        //    }
            //Order.ORDER_ID = test.ToString();
            //try
            //{
            //    pz.SaveChanges();
            //}
            //catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            //{
            //    Exception raise = dbEx;
            //    foreach (var validationErrors in dbEx.EntityValidationErrors)
            //    {
            //        foreach (var validationError in validationErrors.ValidationErrors)
            //        {
            //            string message = string.Format("{0}:{1}",
            //                validationErrors.Entry.Entity.ToString(),
            //                validationError.ErrorMessage);
            //            // raise a new exception nesting
            //            // the current instance as InnerException
            //            raise = new InvalidOperationException(message, raise);
            //        }
            //    }
            //    throw raise;
            //}
            

        
        //protected void CheckoutBtn_Click(object sender, ImageClickEventArgs e)
        //{
        //    using (ShoppingCartActions usersShoppingCart = new ShoppingCartActions())
        //    {
        //        Session["payment_amt"] = usersShoppingCart.GetTotal();
        //    }
        //    Response.Redirect("Checkout/CheckoutStart.aspx");
        //}
    }

}

TestApp/Views/ShoppingCart/Cart.cshtml
@*@using System.Diagnostics.Eventing.Reader
@using System.Globalization*@
@using System.Configuration
@using TestApp.Controllers

<h2>Cart</h2>





<body>
    @*<table class="table-responsive table-bordered table-striped">
        <tr>
            <th>
            Name
            </th>
            <th>
            Price
            </th>
            <th>
            Quantity
            </th>
            <th>
            Sub Total
            </th>
        </tr>
        @foreach (CartItem item in (List<CartItem>)Session["cart"])
        {
            <tr>
                <td>
                @item.Pr.PIZZA_NAME
                 </td>
                <td>
                @item.Pr.UNIT_PRICE
                </td>
                <td>
                @item.Quantity
                 </td>
                <td>
                @(item.Pr.UNIT_PRICE * item.Quantity )
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", "ShoppingCart", new { id = item.Pr.SIZE_ID }, null)
                </td>
                <td>
                    <h3>
                        @Html.ActionLink("+", "AddQt", "ShoppingCart", new { id = item.Pr.SIZE_ID }, null)
                        </h3>
                </td>
                <td>
                    <h3>
                   @Html.ActionLink("-", "RemoveQt", "ShoppingCart", new { id = item.Pr.SIZE_ID }, null)
                </h3>
                </td>
                <td>
                   
                </td>
                
            </tr>



        }

    </table>*@

    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-10 col-md-offset-1">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            
                            <th>Product</th>
                            <th>Quantity</th>
                            <th></th>
                            <th></th>
                            <th class="text-center">Price</th>
                            <th class="text-center">Total</th>
                            <th> </th>
                        </tr>
                    </thead>

                    


                    <tbody>
@foreach (CartItem item in (List<CartItem>)Session["cart"])
{
                        <tr>
                            <td class="col-sm-8 col-md-6">
                                <div class="media">
                                    <a class="thumbnail pull-left" href="#"> <img class="media-object" src="~/Content/@(item.Pr.ITEM_ID).png"  style="width: 72px; height: 72px;"> </a>
                                    <div class="media-body">
                                        <h4 class="media-heading"><a href="#">@item.Pr.ITEM_NAME</a></h4>
                                        
                                    </div>
                                </div>
                            </td>
                            <td class="col-sm-1 col-md-1" style="text-align: center">
                                <input type="email" class="form-control" id="exampleInputEmail1" value="@item.Quantity">
                            </td>
                            @if (item.Quantity == 1) { 
                            <td class="col-sm-1 col-md-1">
                                <button type="button" class="btn disabled">
                                     @Html.ActionLink("-", "RemoveQt", "ShoppingCart", new { id = item.Pr.SIZE_ID }, null)
                                </button>
                                
                            </td>
                            }
                            else
                            {
                                <td class="col-sm-1 col-md-1">
                                    <button type="button" class="btn">
                                        @Html.ActionLink("-", "RemoveQt", "ShoppingCart", new { id = item.Pr.SIZE_ID }, null)
                                    </button>

                                </td>
                            }
                            <td class="col-sm-1 col-md-1">
                                <button type="button" class="btn">
                                     @Html.ActionLink("+", "AddQt", "ShoppingCart", new { id = item.Pr.SIZE_ID }, null)
                                </button>

                            </td>
                            <td class="col-sm-1 col-md-1 text-center"><strong>@item.Pr.UNIT_PRICE</strong></td>
                            <td class="col-sm-1 col-md-1 text-center"><strong>@(item.Pr.UNIT_PRICE * item.Quantity )</strong></td>
                            <td class="col-sm-1 col-md-1">
                                <button type="button" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-remove"></span> @Html.ActionLink("Delete", "Delete", "ShoppingCart", new { id = item.Pr.SIZE_ID }, null)
                                </button>

                            </td>
                            
                        </tr>
                        
                        }

                        
                        

                        <tr>
                            <td>   </td>
                            <td>   </td>
                            <td>   </td>
                            <td><h3>Total</h3></td>
                            <td class="text-right"><h3><strong>@Session["Total"]£</strong></h3></td>
                        </tr>
                        <tr>
                            <td>   </td>
                            <td>   </td>
                            <td>   </td>
                            <td>
                                
                            </td>
                            <td>
                                @if (Session["CustomerId"] != null)
                                {
                                    <form method="post" action="@ConfigurationManager.AppSettings["PayPalSubmitUrl"]">

                                        <input type="hidden" name="upload" value="1" />
                                        <input type="hidden" name="return" value="@ConfigurationManager.AppSettings["returnurl"]" />
                                        <input type="hidden" name="cmd" value="_cart" />
                                        <input type="hidden" name="business" value="@ConfigurationManager.AppSettings["PayPalUsername"]" />


                                        @{int i = 1;
                                            foreach (CartItem item in (List<CartItem>)Session["cart"])
                                            {
                                                <input type="hidden" name="item_name_@i" value="@item.Pr.ITEM_NAME" />
                                                <input type="hidden" name="item_number_@i" value="@item.Pr.SIZE_ID" />
                                                <input type="hidden" name="amount_@i" value="@item.Pr.UNIT_PRICE" />
                                                <input type="hidden" name="quantity_@i" value="@Convert.ToInt32(item.Quantity)" />
                                                i++;
                                            }
                                        }
                                        <input type="hidden" name="hosted_button_id" value="PBWENKJK22G5N">

                                        <input type="image" src="https://www.sandbox.paypal.com/en_US/GB/i/btn/btn_xpressCheckout.gif">

                                    </form>
                                            }
                                            else
                                            {
                                                <h4>You have to Log In to complete the payment</h4>
                                            }
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


</body>

TestApp/Views/ShoppingCart/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>